{{- /* https://github.com/mikutas/linkerd-installation */}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  finalizers:
  - resource-finalizer.argocd.argoproj.io
  name: linkerd
  namespace: {{ .Release.Namespace }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: {{ .Values.linkerd.repoURL }}
      revision: {{ .Values.linkerd.targetRevision }}
      directories:
      - path: booksapp
        exclude: true
      - path: emojivoto
        exclude: true
      - path: podinfo
        exclude: true
      - path: '*'
      pathParamPrefix: chart
  template:
    metadata:
      name: {{ "'{{.chart.path.basename}}'" }}
    spec:
      project: admin
      source:
        path: {{ "'{{.chart.path.path}}'" }}
        repoURL: {{ .Values.linkerd.repoURL }}
        targetRevision: {{ .Values.linkerd.targetRevision }}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ "'{{.chart.path.basename}}'" }}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - kind: Secret
        jsonPointers:
        - /data/tls.crt
        - /data/tls.key
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
      - group: batch
        kind: CronJob
        jsonPointers:
        - /spec/schedule
      - group: apiregistration.k8s.io
        kind: APIService
        jsonPointers:
        - /spec/caBundle
