{{- /* https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#the-default-project */}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  clusterResourceWhitelist: []
  destinations: []
  sourceRepos: []
