repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argo-workflows
  namespace: argo
  createNamespace: true
  chart: argo/argo-workflows
  version: 0.39.0
  values:
  - server:
      ingress:
        enabled: true
        hosts:
        - argowf.local
  hooks:
  # https://argoproj.github.io/argo-workflows/access-token/
  - events: ["postsync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "rbac.yaml"]
