repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argo-workflows
  namespace: argo
  createNamespace: true
  chart: argo/argo-workflows
  version: 0.33.3
  values:
  - server:
      ingress:
        enabled: true
        hosts:
        - argowf.local
  hooks:
  # https://argoproj.github.io/argo-workflows/access-token/#prerequisites
  - events: ["postsync"]
    showlogs: true
    command: kubectl
    args: ["create", "role", "jenkins", "--verb=list,update", "--resource=workflows.argoproj.io", "-n", "argo"]
  - events: ["postsync"]
    showlogs: true
    command: kubectl
    args: ["create", "sa", "jenkins", "-n", "argo"]
  - events: ["postsync"]
    showlogs: true
    command: kubectl
    args: ["create", "rolebinding", "jenkins", "--role=jenkins", "--serviceaccount=argo:jenkins", "-n", "argo"]
  - events: ["postsync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "secret.yaml", "-n", "argo"]
