repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: argo-workflows
  namespace: argo
  createNamespace: true
  chart: argo/argo-workflows
  version: 0.39.2
  values:
  - controller:
      persistence:
        archive: true
        postgresql:
          host: postgresql.argo.svc.cluster.local
          port: 5432
          database: postgres
          tableName: argo_workflows
          userNameSecret:
            name: argo-postgres-config
            key: username
          passwordSecret:
            name: argo-postgres-config
            key: password
      workflowDefaults:
        spec:
          ttlStrategy:
            secondsAfterCompletion: 60
  - server:
      ingress:
        enabled: true
        hosts:
        - argowf.local
  hooks:
  # https://argoproj.github.io/argo-workflows/access-token/
  - events: ["postsync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "rbac.yaml"]
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "-f", "rbac.yaml"]
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "archive.yaml"]
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "-f", "archive.yaml"]

- name: postgresql
  namespace: argo
  chart: bitnami/postgresql
  version: 13.2.9
  values:
  - auth:
      database: postgres
      username: argo
      password: argo
