releases:
  - name: argo-cd
    namespace: argocd
    createNamespace: true
    chart: .
    values:
      - values.yaml
    hooks:
      - events: ["postuninstall"]
        showlogs: true
        command: kubectl
        args: ["delete", "ns", "argocd"]
