repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argo-cd
  namespace: argo-cd
  createNamespace: true
  chart: argo/argo-cd
  version: 5.51.4
  values:
  - configs:
      params:
        "server.insecure": true
  - server:
      ingress:
        enabled: true
        hosts:
        - argocd.local
  hooks:
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "crd", "appprojects.argoproj.io"]
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "crd", "applications.argoproj.io"]
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "crd", "applicationsets.argoproj.io"]
