repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argo-cd
  namespace: argocd
  createNamespace: true
  chart: argo/argo-cd
  version: 6.7.11
  values:
  - configs:
      params:
        "server.insecure": true
  - server:
      ingress:
        enabled: true
        hostname: argocd.local
  hooks:
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "ns", "argocd"]
