releases:
  - name: argo-cd
    namespace: argocd
    createNamespace: true
    chart: .
    values:
      - values.yaml
      - enableCustomResources: false
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: just
        args: ["apply-custom-resources"]
      - events: ["postuninstall"]
        showlogs: true
        command: kubectl
        args: ["delete", "ns", "argocd"]
