enableCustomResources: true

argo-cd:
  fullnameOverride: argo-cd
  configs:
    params:
      "applicationsetcontroller.policy": create-only
      "server.insecure": true
  server:
    ingress:
      enabled: true
      hostname: argocd.local
