{{- if .Values.enableCustomResources }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Chart.Name }}
  source:
    path: {{ .Chart.Name }}
    repoURL: https://github.com/mikutas/helmfiles
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Release.Namespace }}
{{- end }}
