{{- if .Values.enableCustomResources }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Chart.Name }}
  source:
    path: apps/{{ .Chart.Name }}
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-projects
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Chart.Name }}
  source:
    path: helm/app-projects
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
{{- end }}
