name: diff

on: pull_request

jobs:
  diff:
    strategy:
      matrix:
        release-name:
        - argo-cd
        - argo-workflows
        - cert-manager
        - chaos-mesh
        - goldilocks
        - polaris
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.10.1

      - run: |
          just template ${{ matrix.release-name }} > /tmp/pr.yaml

      - uses: actions/checkout@v4
        with:
          ref: main

      - run: |
          just template ${{ matrix.release-name }} > /tmp/main.yaml

      - run: |
          diff /tmp/main.yaml /tmp/pr.yaml --color=always || true
