name: diff

on: pull_request

jobs:
  diff-argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.9.0

      - run: |
          helmfile -f helmfile.yaml template --selector name=argocd > /tmp/pr.yaml

      - uses: actions/checkout@v3
        with:
          ref: main

      - run: |
          helmfile -f helmfile.yaml template --selector name=argocd > /tmp/main.yaml

      - run: |
          diff /tmp/main.yaml /tmp/pr.yaml
