name: manifest

on: pull_request

jobs:
  diff:
    strategy:
      matrix:
        release-name:
        - argo-cd
        - argo-workflows
        - cert-manager
        - chaos-mesh
        - goldilocks
        - polaris
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@v0.2.0

      - run: |
          just template ${{ matrix.release-name }} > /tmp/pr.yaml

      - uses: actions/checkout@v4
        with:
          ref: main

      - run: |
          just template ${{ matrix.release-name }} || true > /tmp/main.yaml

      - run: |
          diff /tmp/main.yaml /tmp/pr.yaml --color=always || true

  polaris:
    strategy:
      matrix:
        release-name:
        - argo-cd
        - argo-workflows
        - cert-manager
        - chaos-mesh
        - goldilocks
        - polaris
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@v0.2.0

      - run: |
          just template ${{ matrix.release-name }} | polaris audit -f pretty --audit-path -
