name: manifest

on: pull_request

jobs:
  diff:
    strategy:
      matrix:
        release-name:
        - argo-cd
        - argo-workflows
        - cert-manager
        - chaos-mesh
        - goldilocks
        - polaris
    uses: ./.github/workflows/reusable-diff.yml
    with:
      release-name: ${{ matrix.release-name }}

  polaris:
    strategy:
      matrix:
        release-name:
        - argo-cd
        - argo-workflows
        - cert-manager
        - chaos-mesh
        - goldilocks
        - polaris
    uses: ./.github/workflows/reusable-polaris.yml
    with:
      release-name: ${{ matrix.release-name }}
