on:
  workflow_call:
    inputs:
      release-name:
        required: true
        type: string

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@v0.2.1

      - run: |
          just template ${{ inputs.release-name }} > /tmp/pr.yaml

      - uses: actions/checkout@v4
        with:
          ref: main
          clean: false

      - run: |
          just template ${{ inputs.release-name }} > /tmp/main.yaml || true

      - run: |
          diff /tmp/main.yaml /tmp/pr.yaml --color=always || true
