on:
  workflow_call:
    inputs:
      changed-dir:
        required: true
        type: string
      artifact-dl-name:
        required: false
        type: string
      artifact-dl-path:
        required: false
        type: string

jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@main

      - if: inputs.artifact-dl-name
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-dl-name }}
          path: ${{ inputs.artifact-dl-path }}

      - run: |
          helmfile -f ${{ inputs.changed-dir }}/helmfile.yaml template | polaris audit -f pretty --audit-path -
