on:
  workflow_call:
    inputs:
      release-name:
        required: true
        type: string
      artifact-dl-name:
        required: false
        type: string
      artifact-dl-path:
        required: false
        type: string

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@v0.2.1

      - if: inputs.artifact-dl-name
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-dl-name }}
          path: ${{ inputs.artifact-dl-path }}

      - run: |
          just template ${{ inputs.release-name }} | tee /tmp/pr.yaml

      - uses: actions/checkout@v4
        with:
          ref: main
          clean: false

      - run: |
          just template ${{ inputs.release-name }} | tee /tmp/main.yaml || true

      - run: |
          diff -u /tmp/main.yaml /tmp/pr.yaml --color=always || true

      - run: |
          dyff --color on between /tmp/main.yaml /tmp/pr.yaml
